use serde::Serialize;

#[derive(Debug, Serialize)]
pub enum UserClass {
    Alchemist,
    Assassin,
    Barbarian,
    Bard,
    Beast,
    Cleric,
    Fighter,
    Jester,
    Lizard,
    Magician,
    Ranger,
    Rouge,
    Sage,
    Thief,
    Undead,
    Hero,
    Titan,
    God,
}

impl UserClass {
    pub fn from_u8(id: &u8) -> Option<UserClass> {
        match id {
            0 => None,
            1 => Some(UserClass::Alchemist),
            2 => Some(UserClass::Assassin),
            3 => Some(UserClass::Barbarian),
            4 => Some(UserClass::Bard),
            5 => Some(UserClass::Beast),
            6 => Some(UserClass::Cleric),
            7 => Some(UserClass::Fighter),
            8 => Some(UserClass::Jester),
            9 => Some(UserClass::Lizard),
            10 => Some(UserClass::Magician),
            11 => Some(UserClass::Ranger),
            12 => Some(UserClass::Rouge),
            13 => Some(UserClass::Sage),
            14 => Some(UserClass::Thief),
            15 => Some(UserClass::Undead),
            16 => Some(UserClass::Hero),
            17 => Some(UserClass::Titan),
            18 => Some(UserClass::God),
            _ => None,
        }
    }
}

#[derive(Debug, Serialize)]
pub enum Weapon {
    Hands,
    Dart,
    Sling,
    Dagger,
    Staff,
    Club,
    Hammer,
    Mace,
    Flail,
    Spear,
    Axe,
    Harpoon,
    ShortBow,
    WarHammer,
    BattleAxe,
    LightCrossbow,
    Javelin,
    ShortSword,
    LongBow,
    LongSword,
    HeavyCrossbow,
    Scimitar,
    PoleArm,
    BroadSword,
    Trident,
    TwoHandedSword,
    GlovesOfStrength,
    DartOfHoming,
    SlingOfSeeking,
    DaggerOfVenom,
    StaffOfStriking,
    HammerOfThrowing,
    MaceOfDisruption,
    AxeOfHurling,
    HammerOfThunderbolts,
    AxeOfLords,
    CrossbowOfDistance,
    SwordOfQuickness,
    ArrowsOfSlaying,
    SwordOfSharpness,
    CrossbowOfAccuracy,
    ScimitarOfSpeed,
    SwordOfWounding,
    TridentOfSubmission,
    VorpalSword,
    WandOfWonder,
    RodOfSmiting,
    SwordOfLifeStealing,
    WandOfLightning,
    RingOfShootingStars,
    StaffOftheMagi,
    DaggerOfDeath,
    HammerOfHeros,
    TridentOfTitans,
    WrathOfGod,
}

impl Weapon {
    pub fn from_u8(id: &u8) -> Weapon {
        match id {
            0 => Weapon::Hands,
            1 => Weapon::Dart,
            2 => Weapon::Sling,
            3 => Weapon::Dagger,
            4 => Weapon::Staff,
            5 => Weapon::Club,
            6 => Weapon::Hammer,
            7 => Weapon::Mace,
            8 => Weapon::Flail,
            9 => Weapon::Spear,
            10 => Weapon::Axe,
            11 => Weapon::Harpoon,
            12 => Weapon::ShortBow,
            13 => Weapon::WarHammer,
            14 => Weapon::BattleAxe,
            15 => Weapon::LightCrossbow,
            16 => Weapon::Javelin,
            17 => Weapon::ShortSword,
            18 => Weapon::LongBow,
            19 => Weapon::LongSword,
            20 => Weapon::HeavyCrossbow,
            21 => Weapon::Scimitar,
            22 => Weapon::PoleArm,
            23 => Weapon::BroadSword,
            24 => Weapon::Trident,
            25 => Weapon::TwoHandedSword,
            26 => Weapon::GlovesOfStrength,
            27 => Weapon::DartOfHoming,
            28 => Weapon::SlingOfSeeking,
            29 => Weapon::DaggerOfVenom,
            30 => Weapon::StaffOfStriking,
            31 => Weapon::HammerOfThrowing,
            32 => Weapon::MaceOfDisruption,
            33 => Weapon::AxeOfHurling,
            34 => Weapon::HammerOfThunderbolts,
            35 => Weapon::AxeOfLords,
            36 => Weapon::CrossbowOfDistance,
            37 => Weapon::SwordOfQuickness,
            38 => Weapon::ArrowsOfSlaying,
            39 => Weapon::SwordOfSharpness,
            40 => Weapon::CrossbowOfAccuracy,
            41 => Weapon::ScimitarOfSpeed,
            42 => Weapon::SwordOfWounding,
            43 => Weapon::TridentOfSubmission,
            44 => Weapon::VorpalSword,
            45 => Weapon::WandOfWonder,
            46 => Weapon::RodOfSmiting,
            47 => Weapon::SwordOfLifeStealing,
            48 => Weapon::WandOfLightning,
            49 => Weapon::RingOfShootingStars,
            50 => Weapon::StaffOftheMagi,
            51 => Weapon::DaggerOfDeath,
            52 => Weapon::HammerOfHeros,
            53 => Weapon::TridentOfTitans,
            54 => Weapon::WrathOfGod,
            _ => Weapon::Hands,
        }
    }
}

#[derive(Debug, Serialize)]
pub enum Armor {
    Skin,
    WoodenShield,
    SmallShield,
    LargeShield,
    Leather,
    PaddedLeather,
    StuddedLeather,
    RingMail,
    ScaleMail,
    ChainMail,
    SplintMail,
    BandedMail,
    BronzePlateMail,
    NormalPlateMail,
    FieldPlateArmor,
    FullPlateArmor,
    DancingShield,
    DragonScaleMail,
    ElfinChainMail,
    MinthralPlateArmor,
    CloakOfElvenkind,
    RobeOfBlending,
    AdamantitePlateMail,
    CloakOfDisplacement,
    CubeOfForce,
    RingOfInvisibility,
    RingOfInsanity,
    MagicShield,
    TitaniumArmor,
    DivineSphere,
}

impl Armor {
    pub fn from_u8(id: &u8) -> Armor {
        match id {
            0 => Armor::Skin,
            1 => Armor::WoodenShield,
            2 => Armor::SmallShield,
            3 => Armor::LargeShield,
            4 => Armor::Leather,
            5 => Armor::PaddedLeather,
            6 => Armor::StuddedLeather,
            7 => Armor::RingMail,
            8 => Armor::ScaleMail,
            9 => Armor::ChainMail,
            10 => Armor::SplintMail,
            11 => Armor::BandedMail,
            12 => Armor::BronzePlateMail,
            13 => Armor::NormalPlateMail,
            14 => Armor::FieldPlateArmor,
            15 => Armor::FullPlateArmor,
            16 => Armor::DancingShield,
            17 => Armor::DragonScaleMail,
            18 => Armor::ElfinChainMail,
            19 => Armor::MinthralPlateArmor,
            20 => Armor::CloakOfElvenkind,
            21 => Armor::RobeOfBlending,
            22 => Armor::AdamantitePlateMail,
            23 => Armor::CloakOfDisplacement,
            24 => Armor::CubeOfForce,
            25 => Armor::RingOfInvisibility,
            26 => Armor::RingOfInsanity,
            27 => Armor::MagicShield,
            28 => Armor::TitaniumArmor,
            29 => Armor::DivineSphere,
            _ => Armor::Skin,
        }
    }
}
